services:
  opensearch:
    image: opensearchproject/opensearch:2.19.0
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=
    ports:
      - "9200:9200"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - opensearch

  fluent-bit:
    image: fluent/fluent-bit:3.1
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - opensearch
      - app